vim.cmd("set expandtab")
vim.cmd("set shiftwidth=2")
vim.cmd("set softtabstop=2")
vim.cmd("set tabstop=2")
vim.cmd("set noswapfile")
vim.cmd("set ignorecase")
vim.cmd("set smartcase")
vim.cmd("set number")
vim.cmd("set termguicolors")
vim.cmd("set clipboard=unnamedplus")
vim.g.mapleader = " "
