#!/bin/sh

# Increment or decrement the brightness and send a notification
# of the current brightness level.

send_notification() {
	brightness=$(cat /sys/class/backlight/intel_backlight/actual_brightness)
  max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
  brightness_percentage=$((brightness * 100 / max_brightness))
  dunstify -a "changebrightness" -u normal -r 9994 -h int:value:"$brightness_percentage" -i "brightness-$1" "Brightness" "Currently at ${brightness_percentage}%" -t 2000
}

case $1 in
up)
  brightnessctl s +5%
  send_notification "$1"
	;;
down)
  brightnessctl s 5%-
  send_notification "$1"
	;;
esac
