#!/bin/sh

# Increment or decrement the brightness and send a notification
# of the current brightness level.

send_notification() {
	brightness=$(cat /sys/class/backlight/acpi_video0/actual_brightness)
  max_brightness=$(cat /sys/class/backlight/acpi_video0/max_brightness)
  brightness_percentage=$((brightness * 100 / max_brightness))
  notify-send -a brightnessctl -i ~/.config/custom_scripts/icons/brightness-$1.png -u normal -r 9994 -h int:value:"$brightness_percentage" "Brightness" "Currently at ${brightness_percentage}" -t 2000
}

case $1 in
up)
  brightnessctl s +5%
  send_notification "$1"
	;;
down)
  brightnessctl s 5%-
  send_notification "$1"
	;;
esac
