#!/bin/sh

# Increment, decrement, or mute the volume and send a notification
# of the current volume level.

send_notification() {
	volume=$(pamixer --get-volume)
  notify-send -a pavucontrol -i ~/.config/custom_scripts/icons/volume-$1.png -u normal -r 9993 -h int:value:"$volume" "Volume" "Currently at ${volume}" -t 2000
}

case $1 in
up)
	# Set the volume on (if it was muted)
	pamixer -u
	pamixer -i 5
	send_notification "$1"
	;;
down)
	pamixer -u
	pamixer -d 5
	send_notification "$1"
	;;
mute)
	pamixer -t
	if eval "$(pamixer --get-mute)"; then
		notify-send -a pavucontrol -i ~/.config/custom_scripts/icons/volume-$1.png "Volume" "Muted" -u normal -r 9993 -t 2000
	else
		send_notification up
	fi
	;;
esac
